=begin
#TODO: opportunities?
#TODO: Search for support call screeners
#TODO: Address field or model for contracts (Locations model??)
#TODO: Determine if additional indexes are needed
#TODO: GUID for Troy & accounting on each contract
#TODO: use account id instead of account name for aggregation, etc.
#TODO: Need to move support levels to line items
#TODO: more detailed support levels, multiple fields
#TODO: some sort of reminder system to follow up on certain items -- maybe dovetails into reminders for expired/expiring contracts

#TODO: Link on Account Names to see all contracts for that account
#TODO: Add blank default selection to product line in dropdown on support price add and edit
#TODO: Total renewals, using javascript to update total when filtering
#TODO: Dashboard or Admin - report for totals by product line
#TODO: Dashboard report - Add columns to total up expired contracts and subtract them from the total
#TODO: Admin Report - uncategorized items
#TODO: Global todo list (uncat items, renewals, upfront contracts)
#TODO: Comments report, - maybe with RSS feed


#TODO: Get product deals working

#TODO: Line Items export expanded to include other columns, provider, Notes...

OTHER STUFF (AUTOGENERATED):

app/controllers/contracts_controller.rb:
  * [  8] show current contracts, including those marked expired

app/controllers/ioscans_controller.rb:
  * [ 16] move work to an Ioscan model

app/controllers/line_items_controller.rb:
  * [ 94] check filtering based on submit button clicked.

app/controllers/reports_controller.rb:
  * [  2] Add filtering based on role to allow viewing of reports
  * [ 76] Change to AJAX requests for report?

app/controllers/swlists_controller.rb:
  * [  7] Move to an Swlist model

app/models/line_item.rb:
  * [157] add translation table support
  * [162] WIP

app/models/server.rb:
  * [ 10] override tier setter and getter methods to provide automatic translation between integrity and pa_risc tiers.

app/models/support_deal.rb:
  * [115] Use passed parameters to determine if expired are shown.
  * [255] Make a view for this, or make the current view work with both.
  * [482] WIP

app/models/support_pricing_db.rb:
  * [ 49] Timezone checks

=end

