--- !ruby/object:User 
attributes: 
  salt: 7e3041ebc2fc05a40c60028e2c4901a81035d3cd
  updated_at: 2008-08-11 12:24:50
  crypted_password: 098f6bcd4621d373cade4e832627b4f6
  role: \"35\"
  remember_token_expires_at: 
  id: \"1\"
  office: Dallas, TX
  remember_token: 
  sugar_id: 
  first_name: Troy
  last_name: Nini
  login: tnini
  created_at: 2008-08-11 00:00:00
  email: tnini@sourcedirect.com

